package com.example.hackfestciputra2023.util

enum class NavRoute {
    SPLASH,
    LOGIN,
    POSTLOGIN,
    REGISTER,
    ONBOARDING,
    HOME,
    PROFILE,
    BAYAR,
    USER_PICK_LOCATION,
    PRODUCT_SERVICE_AROUND,
    PRODUCT_SERVICE_DETAIL,
    PRODUCT_SERVICE_MOST_REQUESTED,
    PRODUCT_SERVICE_OPEN24,
    MAP_DETAIL,
    WEBVIEW,
    BAYAR_INSERT_AMOUNT
}